-- single line comment
/*
multi line 
comment 
*/
-- mysql is not case sensitive
-- show databases; this will list all the available databases.
-- command enter for executing line
show databases;


create database test1; -- this will create a database with a name

use test1;
create table student
(
id int,
stdname varchar(20),
stdDOB date);

show tables;
describe student;

-- delete database: Drop database with name;

create database college;
use college;

create table student 
(
stdid int primary key auto_increment,
stdname varchar(20) not null,
stdage int check(stdage>=18),
stdLocation varchar(25) default 'london'
);

describe student; -- this shows the data in the table.

/*
inserting data into tablename (column name1, columnname2 ...) values (value1, value2...)
*/

insert into student (stdname, stdage, stdLocation) values ('mark',20,'manchester');
select * from student; -- this selects from the rows in the table

-- inserting incorrect data (age is not 18 or over);
 -- insert into student (stdname, stdage, stdLocation) values ('james',16,'manchester');

insert into student (stdname, stdage) values ('matt',20);
select * from student;

/*
-- Create database with any name
-- create this table and insert the data into the tables as well
-- mark column shouldn't accept value greater than 100 and less than 0
-- the gender column should only accept female or male values
-- make the id to be generated by MySQL
*/

create table info
(
infoid int primary key auto_increment,
infoname varchar(30) not null,
infoclass varchar(10) not null,
infomark int check(infomark < 100 and infomark > 0),
infogender varchar(6) check(infogender = 'male' or infogender = 'female')
);

insert into info (infoname, infoclass, infomark, infogender) values ('john deo','Four',75,'female');
insert into info (infoname, infoclass, infomark, infogender) values ('max ruin','Three',85,'male');
insert into info (infoname, infoclass, infomark, infogender) values ('Arnold','Three',55,'female');
insert into info (infoname, infoclass, infomark, infogender) values ('Krish Star','Four',60,'female');
insert into info (infoname, infoclass, infomark, infogender) values ('John Mike','Four',60,'female');
insert into info (infoname, infoclass, infomark, infogender) values ('Alex John','Four',55,'male');
insert into info (infoname, infoclass, infomark, infogender) values ('My John Rob','Five',78,'male');
insert into info (infoname, infoclass, infomark, infogender) values ('Asruid','Five',85,'male');
insert into info (infoname, infoclass, infomark, infogender) values ('Tes Qry','Six',78,'male');
insert into info (infoname, infoclass, infomark, infogender) values ('Big John','Four',55,'female');

select * from info;

-- updating data in mysql

/*
update table set column='newvalue, column2='newvalue' where condition
*/

update info set infoname='james',infomark=95 where infoid=3;
select * from info;

use college;
select * from info;

-- Deleting data: delete from tableName where condition
SET SQL_SAFE_UPDATES = 0;
delete from info where infoname='john deo';
select * from info;

-- truncating data: truncate table name
truncate info;

-- drop syntax: 
-- drop table tablename
-- drop database

-- rollback = undo, we cannot rollback data which is deleted with truncate or drop;
-- to restore backup;

-- disable default commit (accepting thr changes), once the changes are commited we cannot rollback
set autocommit=0;

insert into info (infoname, infoclass, infomark, infogender) values ('john deo','Four',75,'female');
select * from info;
commit;
insert into info (infoname, infoclass, infomark, infogender) values ('Henry','Three',85,'Male');
rollback;

-- add age column to the learners table
-- columns are added to the end 
alter table info add column age int;
describe info;
-- add column at a specific location:

alter table info add column preferredName varchar(30) after infoname;
describe info;

-- delete the age column:
alter table info drop column age;

-- change the length of preferredNamecolumn to 250 characters.
alter table info modify column preferredName varchar(50); 

-- change the name of the column:
alter table info rename column preferredName to givenName;

-- change column name:
alter table info rename to students;
describe students;

-- remove primary key from the id:
alter table students drop primary key;


-- 11:14:48	alter table students drop primary key	Error Code: 1075. Incorrect table definition; there can be only one auto column and it must be defined as a key	0.00042 sec
-- auto incriment must be a primary key. we first need to remove auto incriment

alter table students modify column infoid int;


-- add primary key to another column:

alter table students add primary key(infoid);


-- task: add a column to the table which already exists. Rename one of of the columns. remove primary key and add the primary key back.

alter table students add column infolocation int first;
alter table students rename column infolocation to location;
alter table students drop primary key;
alter table students add primary key(infoid);

create database world;
use world;

create table country 
(
	Code  int primary key,
	Name varchar(20),
	continent varchar(20),
	population decimal(30, 3),
	capital int 
);
create table city
(
id int primary key auto_increment,
name varchar(20) not null,
countryCode int,
capital int

);
create table countryLanguage
(
countryCode int,
language varchar(25) not null,
isOfficial boolean,
percentage decimal(10,3)
);

/*
Add foreign key:
alter table add foreign key (column name) references primarykeytablename (primarykeycolumnname)
*/

alter table country add foreign key(capital) references city(id);
alter table city add foreign key(countryCode) references country(code);
alter table countryLanguage add foreign key(countryCode) references country(Code);



